//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Insupan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARGUE_DEVOLUCIONES
    {
        public string DEVOLUCION_ID { get; set; }
        public string ASESOR_ID { get; set; }
        public System.DateTime FECHA_ERP { get; set; }
        public string ESTADO_ERP { get; set; }
        public string DOC_REFERENCIA { get; set; }
        public string NUMERO_NOTA_CREDITO { get; set; }
    }
}
