//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Insupan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTERA_DOCUMENTOS
    {
        public string DOCUMENTO_ID { get; set; }
        public string CLIENTE_ID { get; set; }
        public string TIPO_DOCUMENTO { get; set; }
        public string NUMERO_REFERENCIA { get; set; }
        public string DOC_REFERENCIA { get; set; }
        public Nullable<System.DateTime> FECHA_DOCUMENTO { get; set; }
        public Nullable<System.DateTime> FECHA_BASE { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO { get; set; }
        public Nullable<decimal> VALOR_BASE { get; set; }
        public Nullable<decimal> VALOR_TOTAL { get; set; }
        public Nullable<decimal> SALDO_PENDIENTE { get; set; }
        public string CONDICION_COMERCIAL_ID { get; set; }
        public Nullable<decimal> PORCENTAJE_DESCUENTO1 { get; set; }
        public Nullable<decimal> PORCENTAJE_DESCUENTO2 { get; set; }
        public Nullable<decimal> PORCENTAJE_DESCUENTO3 { get; set; }
        public Nullable<decimal> PORCENTAJE_DESCUENTO4 { get; set; }
        public Nullable<decimal> DIAS_PORC_DSCTO1 { get; set; }
        public Nullable<decimal> DIAS_PORC_DSCTO2 { get; set; }
        public Nullable<decimal> DIAS_PORC_DSCTO3 { get; set; }
        public Nullable<decimal> DIAS_PORC_DSCTO4 { get; set; }
        public Nullable<decimal> PORC_DESCUENTO_MIN1 { get; set; }
        public Nullable<decimal> PORC_DESCUENTO_MAX1 { get; set; }
        public Nullable<decimal> PORC_DESCUENTO_MIN2 { get; set; }
        public Nullable<decimal> PORC_DESCUENTO_MAX2 { get; set; }
        public Nullable<decimal> PORC_DESCUENTO_MIN3 { get; set; }
        public Nullable<decimal> PORC_DESCUENTO_MAX3 { get; set; }
        public Nullable<decimal> PORC_DESCUENTO_MIN4 { get; set; }
        public Nullable<decimal> PORC_DESCUENTO_MAX4 { get; set; }
        public Nullable<decimal> VALOR_IVA { get; set; }
        public string OBSERVACIONES { get; set; }
        public string CAMPO1 { get; set; }
        public string CAMPO2 { get; set; }
        public string CAMPO3 { get; set; }
        public string CAMPO4 { get; set; }
        public string CAMPO5 { get; set; }
        public string FILTRO1 { get; set; }
        public string FILTRO2 { get; set; }
        public string FILTRO3 { get; set; }
    }
}
