//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Insupan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTERA_TIPOS_DOC
    {
        public string TIPO_DOCUMENTO_ID { get; set; }
        public string OPERADOR { get; set; }
        public string DESCRIPCION { get; set; }
        public string CLIENTE_ID { get; set; }
        public string TIPO_IDENTIFICACION_ID { get; set; }
        public string NIT { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string CIIU { get; set; }
        public string TIPO_CLIENTE_ID { get; set; }
        public string LISTA_PRECIOS_ID { get; set; }
        public string TIPO_PERSONA_ID { get; set; }
        public string CONDICION_COMERCIAL_ID { get; set; }
        public Nullable<decimal> CUPO_CREDITO { get; set; }
        public string BLOQUEO_PEDIDOS { get; set; }
        public Nullable<decimal> PED_DIAS_DESPACHO { get; set; }
        public Nullable<decimal> PED_VALOR_MINIMO { get; set; }
        public string ETAPA_ACTUAL { get; set; }
        public string TIPO_VENTA { get; set; }
        public Nullable<decimal> PORC_RETEFUENTE { get; set; }
        public string CAMPO1 { get; set; }
        public string CAMPO2 { get; set; }
        public string CAMPO3 { get; set; }
        public string CAMPO4 { get; set; }
        public string CAMPO5 { get; set; }
        public string CAMPO6 { get; set; }
        public string CAMPO7 { get; set; }
        public string CAMPO8 { get; set; }
        public string CAMPO9 { get; set; }
        public string CAMPO10 { get; set; }
        public string CLASE_CLIENTE_ID { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION_ERP { get; set; }
        public Nullable<decimal> PORC_RETEICA { get; set; }
        public Nullable<decimal> PORC_CREE { get; set; }
    }
}
