//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Insupan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES_UBICACIONES
    {
        public string CLIENTE_ID { get; set; }
        public string UBICACION_ID { get; set; }
        public string NOMBRE_UBICACION { get; set; }
        public string PAIS_ID { get; set; }
        public string DEPARTAMENTO_ID { get; set; }
        public string CIUDAD_ID { get; set; }
        public string ZONA_ID { get; set; }
        public string BARRIO { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<decimal> LATITUD { get; set; }
        public Nullable<decimal> LONGITUD { get; set; }
        public string ES_PUNTO_VISITA { get; set; }
        public string ES_PUNTO_ENVIO { get; set; }
    }
}
