//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Insupan
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.Xml.Serialization;

    public partial class CUENTA_BANCARIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUENTA_BANCARIA()
        {
            this.DOCUMENTOS_CC = new HashSet<DOCUMENTOS_CC>();
        }
    
        public string CUENTA_BANCO { get; set; }
        public string NOMBRE { get; set; }
        public string ENTIDAD_FINANCIERA { get; set; }
        public string MONEDA { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO1 { get; set; }
        public string TELEFONO2 { get; set; }
        public string CONTACTO { get; set; }
        public string CARGO { get; set; }
        public string FORMATO { get; set; }
        public System.DateTime FECHA_ULT_MOV { get; set; }
        public decimal SALDO { get; set; }
        public decimal SALDO_BANCOS { get; set; }
        public decimal POSICION_DE_CAJA { get; set; }
        public decimal SALDO_ANTERIOR { get; set; }
        public decimal TIPO_CAMBIO_LOCAL { get; set; }
        public decimal TIPO_CAMBIO_DOLAR { get; set; }
        public string ACTIVA { get; set; }
        public decimal ULTIMO_DEPOSITO { get; set; }
        public decimal ULTIMA_TEFCR { get; set; }
        public decimal LIMITE_SOBREGIRO { get; set; }
        public string CTR_CONTABLE { get; set; }
        public string CTA_CONTABLE { get; set; }
        public string CTR_CIERRE_DEB { get; set; }
        public string CTA_CIERRE_DEB { get; set; }
        public string CTR_CIERRE_CRED { get; set; }
        public string CTA_CIERRE_CRED { get; set; }
        public decimal ULTIMA_NOTACR { get; set; }
        public Nullable<decimal> ULTIMO_CHEQUE { get; set; }
        public decimal ULTIMO_OTROCR { get; set; }
        public Nullable<decimal> ULTIMA_TEFDB { get; set; }
        public decimal ULTIMA_NOTADB { get; set; }
        public decimal ULTIMO_OTRODB { get; set; }
        public Nullable<int> ULTIMA_CONCIL { get; set; }
        public string MODO_CONCILIAR { get; set; }
        public string IDIOMA_MON_LETRAS { get; set; }
        public string TIPO_CRED_AJUSTE { get; set; }
        public Nullable<short> SUBTIPO_CRED_AJUST { get; set; }
        public string TIPO_DEB_AJUSTE { get; set; }
        public Nullable<short> SUBTIPO_DEB_AJUST { get; set; }
        public string PERMITE_SOBREGIRO { get; set; }
        public string CTA_AJUSTE_CRED { get; set; }
        public System.DateTime FCH_HORA_CREACION { get; set; }
        public string USUARIO_CREACION { get; set; }
        public string CTR_AJUSTE_DEB { get; set; }
        public string CTR_GASTO_TRANSF { get; set; }
        public string CTA_AJUSTE_DEB { get; set; }
        public string CTA_GASTO_TRANSF { get; set; }
        public string CTR_LIQUIDAR_CRED { get; set; }
        public string CTA_LIQUIDAR_CRED { get; set; }
        public string CTR_LIQUIDAR_DEB { get; set; }
        public string CTA_LIQUIDAR_DEB { get; set; }
        public string CTR_AJUSTE_CRED { get; set; }
        public Nullable<System.DateTime> FCH_HORA_MODIFIC { get; set; }
        public string USUARIO_MODIFIC { get; set; }
        public string PERMITE_TRANSF_IC { get; set; }
        public string CTA_TRANSF_IC { get; set; }
        public string CTR_TRANSF_IC { get; set; }
        public string RUBRO1_CTABANCO { get; set; }
        public string RUBRO2_CTABANCO { get; set; }
        public string RUBRO3_CTABANCO { get; set; }
        public string RUBRO4_CTABANCO { get; set; }
        public string RUBRO5_CTABANCO { get; set; }
        public string RUBRO6_CTABANCO { get; set; }
        public string RUBRO7_CTABANCO { get; set; }
        public string RUBRO8_CTABANCO { get; set; }
        public string RUBRO9_CTABANCO { get; set; }
        public string RUBRO10_CTABANCO { get; set; }
        public string CONSE_CHEQUE { get; set; }
        public string CONSE_TEF { get; set; }
        public string TIPO_CUENTA { get; set; }
        public string CTR_DOC_GP { get; set; }
        public string CTA_DOC_GP { get; set; }
        public decimal SALDO_TRANS { get; set; }
        public decimal SALDO_TRANS_LOCAL { get; set; }
        public decimal SALDO_TRANS_DOLAR { get; set; }
        public string PERMITE_DOC_GP { get; set; }
        public string PARTICIPA_FLUJOCAJA { get; set; }
        public string CTA_ELECTRONICA { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [XmlIgnore]
        [IgnoreDataMember]
        public virtual ICollection<DOCUMENTOS_CC> DOCUMENTOS_CC { get; set; }
    }
}
