//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Insupan
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PEDIDOS
    {
        public string PEDIDO_ID { get; set; }
        public string ASESOR_ID { get; set; }
        public string PRODUCTO_ID { get; set; }
        public string PRESENTACION_ID { get; set; }
        public Nullable<decimal> CANTIDAD_UNIDADES_BASE { get; set; }
        public Nullable<decimal> CANTIDAD_PRESENTACION { get; set; }
        public Nullable<decimal> PRECIO_BASE { get; set; }
        public Nullable<decimal> VALOR_BRUTO { get; set; }
        public string TIPO_DESCUENTO { get; set; }
        public Nullable<decimal> DESCUENTO { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> SUBTOTAL_SIN_IVA { get; set; }
        public string ESTADO { get; set; }
        public string OBSERVACIONES { get; set; }
        public string BODEGA_ID { get; set; }
    }
}
