//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Insupan
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVOLUCION
    {
        public string DEVOLUCION1 { get; set; }
        public string USUARIO_CREADO { get; set; }
        public string AJUSTE_CONFIG { get; set; }
        public string EMBARQUE { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> AUDIT_TRANS_INV { get; set; }
        public string TIPO_DEVOLUCION { get; set; }
        public System.DateTime FECHA_DEVOLUCION { get; set; }
        public string AFECTA_ORDEN { get; set; }
        public string DOCUMENTO_DEBITO { get; set; }
        public string ASIENTO { get; set; }
        public string NOTAS { get; set; }
        public string NUMERO_DEBITO { get; set; }
        public Nullable<short> SUBTIPO { get; set; }
        public Nullable<System.DateTime> FECHA_DOCDEBITO { get; set; }
        public string APLICACION { get; set; }
        public System.DateTime FECHA_HORA_CREADO { get; set; }
        public Nullable<System.DateTime> FECHA_HORA_APLIC { get; set; }
        public Nullable<System.DateTime> FECHA_HORA_CANCELA { get; set; }
        public string USUARIO_APLICADO { get; set; }
        public string USUARIO_CANCELA { get; set; }
        public string MONEDA_DDEB { get; set; }
        public string PROVEEDOR_DDEB { get; set; }
        public Nullable<decimal> TC_MONEDA_LOCAL { get; set; }
        public Nullable<decimal> TC_MONEDA_DOLAR { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> FECHA_CAI { get; set; }
        public string CAI { get; set; }
        public string TIPO_AFECTACION_IVA { get; set; }
        public string TIPO_IMPUESTO { get; set; }
        public string TIPO_TARIFA { get; set; }
        public Nullable<decimal> PORC_AFECTACION_IVA { get; set; }
        public Nullable<decimal> MontoTotalImpuestoAcreditar { get; set; }
        public Nullable<decimal> MontoTotalDeGastoAplicable { get; set; }
        public Nullable<decimal> MontoProporcionalidad { get; set; }
    }
}
