//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Insupan
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCABEZADO_PEDIDOS
    {
        public string PEDIDO_ID { get; set; }
        public string FACTURA_ID { get; set; }
        public string CLIENTE_ID { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string HORA { get; set; }
        public string DIRECCION_DESPACHO { get; set; }
        public Nullable<decimal> VALOR_BRUTO { get; set; }
        public Nullable<decimal> VALOR_DESCUENTO { get; set; }
        public Nullable<decimal> OTROS_DESCUENTO { get; set; }
        public Nullable<decimal> VALOR_IVA { get; set; }
        public Nullable<decimal> VALOR_NETO { get; set; }
        public Nullable<decimal> VALOR_TOTAL { get; set; }
        public string OBSERVACIONES { get; set; }
        public string ESTADO { get; set; }
        public string MOTIVO { get; set; }
        public string ASESOR_ID { get; set; }
        public Nullable<System.DateTime> FECHA_ENTREGA { get; set; }
        public string TIPO_FACTURA { get; set; }
        public string CAMPO1 { get; set; }
        public string CAMPO2 { get; set; }
        public string CAMPO3 { get; set; }
        public string CAMPO4 { get; set; }
        public string CAMPO5 { get; set; }
        public string CAMPO6 { get; set; }
        public string CAMPO7 { get; set; }
        public string CAMPO8 { get; set; }
        public string CAMPO9 { get; set; }
        public string CAMPO10 { get; set; }
        public string TIPO_PAGO { get; set; }
        public Nullable<decimal> VALOR_FLETE { get; set; }
    }
}
