//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Insupan
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCABEZADO_RECAUDOS
    {
        public string RECAUDO_ID { get; set; }
        public string ASESOR_ID { get; set; }
        public string PREIMPRESO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string CLIENTE_ID { get; set; }
        public Nullable<decimal> TOTAL_EFECTIVO { get; set; }
        public Nullable<decimal> TOTAL_CHEQUE { get; set; }
        public Nullable<decimal> TOTAL_CONSIGNACION { get; set; }
        public Nullable<decimal> TOTAL_RECAUDO { get; set; }
        public string OBSERVACIONES { get; set; }
        public string ESTADO_RECAUDO { get; set; }
        public string NUM_COMPROB_RETENCION { get; set; }
        public Nullable<System.DateTime> FECHA_COMPROB_RETENCION { get; set; }
        public Nullable<decimal> VALOR_COMPROB_RETENCION { get; set; }
    }
}
