//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Insupan
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENCABEZADO_DEVOLUCIONES
    {
        public string ASESOR_ID { get; set; }
        public string DEVOLUCION_ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public string CLIENTE_ID { get; set; }
        public string MOTIVO_ID { get; set; }
        public string OBSERVACIONES { get; set; }
        public decimal VALOR_DEVOLUCION { get; set; }
    }
}
