//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Insupan
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    using System.Xml.Serialization;

    public partial class IMPUESTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IMPUESTO()
        {
            this.ARTICULO = new HashSet<ARTICULO>();
            this.CLIENTE = new HashSet<CLIENTE>();
            this.DOCUMENTOS_CC = new HashSet<DOCUMENTOS_CC>();
        }
    
        public string IMPUESTO1 { get; set; }
        public string DESCRIPCION { get; set; }
        public decimal IMPUESTO11 { get; set; }
        public decimal IMPUESTO2 { get; set; }
        public string USA_IMPUESTO2_CANTIDAD { get; set; }
        public Nullable<decimal> IMPUESTO2_CANTIDAD { get; set; }
        public string CTR_IMP1_GEN { get; set; }
        public string CTA_IMP1_GEN { get; set; }
        public string CTR_IMP2_GEN { get; set; }
        public string CTA_IMP2_GEN { get; set; }
        public string CTR_IMP1_GEN_VTS { get; set; }
        public string CTA_IMP1_GEN_VTS { get; set; }
        public string CTR_IMP2_GEN_VTS { get; set; }
        public string CTA_IMP2_GEN_VTS { get; set; }
        public string CTR_IMP1_DESC_CMPS { get; set; }
        public string CTA_IMP1_DESC_CMPS { get; set; }
        public string CTR_IMP2_DESC_CMPS { get; set; }
        public string CTA_IMP2_DESC_CMPS { get; set; }
        public string CTR_IMP1_DEV_CMPS { get; set; }
        public string CTA_IMP1_DEV_CMPS { get; set; }
        public string CTR_IMP2_DEV_CMPS { get; set; }
        public string CTA_IMP2_DEV_CMPS { get; set; }
        public string CTR_IMP1_DEV_VTS { get; set; }
        public string CTA_IMP1_DEV_VTS { get; set; }
        public string CTR_IMP2_DEV_VTS { get; set; }
        public string CTA_IMP2_DEV_VTS { get; set; }
        public string TIPO_CONTAB_IMP1 { get; set; }
        public string TIPO_CONTAB_IMP2 { get; set; }
        public string CONTAB_DEV_IMP1 { get; set; }
        public string CONTAB_DEV_IMP2 { get; set; }
        public string CALCULO_IMP2 { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string U_IMPUESTO1_SAT { get; set; }
        public string U_IMPUESTO2_SAT { get; set; }
        public string TIPO_IMPUESTO1 { get; set; }
        public string TIPO_IMPUESTO2 { get; set; }
        public string U_IMPUESTO { get; set; }
        public string U_IMPUESTO2 { get; set; }
        public string TIPO_TARIFA1 { get; set; }
        public string TIPO_TARIFA2 { get; set; }
        public string ESTADO { get; set; }
        public string U_IMPUESTO_EXCLUIDO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [XmlIgnore]
        [IgnoreDataMember]
        public virtual ICollection<ARTICULO> ARTICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [XmlIgnore]
        [IgnoreDataMember]
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [XmlIgnore]
        [IgnoreDataMember]
        public virtual ICollection<DOCUMENTOS_CC> DOCUMENTOS_CC { get; set; }
    }
}
