//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Insupan
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTA_DIF_RECAUDO
    {
        public string RECAUDO_ID { get; set; }
        public string ASESOR_ID { get; set; }
        public string FACTURA_ID { get; set; }
        public string DIFERENCIA_ID { get; set; }
        public Nullable<decimal> VALOR_DIFERENCIA { get; set; }
        public string OBSERVACIONES { get; set; }
        public string DATO_COMPLEMENTARIO { get; set; }
    }
}
