//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Insupan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsupanEntities : DbContext
    {
        public InsupanEntities()
            : base("name=InsupanEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTE_RETENCION> CLIENTE_RETENCION { get; set; }
        public virtual DbSet<EXISTENCIA_BODEGA> EXISTENCIA_BODEGA { get; set; }
        public virtual DbSet<PEDIDO> PEDIDO { get; set; }
        public virtual DbSet<PEDIDO_LINEA> PEDIDO_LINEA { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<ARTICULO> ARTICULO { get; set; }
        public virtual DbSet<CUENTA_BANCARIA> CUENTA_BANCARIA { get; set; }
        public virtual DbSet<DOCUMENTOS_CC> DOCUMENTOS_CC { get; set; }
        public virtual DbSet<NIVEL_PRECIO> NIVEL_PRECIO { get; set; }
        public virtual DbSet<DEVOLUCION> DEVOLUCION { get; set; }
        public virtual DbSet<ASIGNACION_BODEGAS> ASIGNACION_BODEGAS { get; set; }
        public virtual DbSet<ASIGNACION_CLIENTES> ASIGNACION_CLIENTES { get; set; }
        public virtual DbSet<BANCOS_CUENTAS> BANCOS_CUENTAS { get; set; }
        public virtual DbSet<CARTERA_DOCUMENTOS> CARTERA_DOCUMENTOS { get; set; }
        public virtual DbSet<CARTERA_TIPOS_DOC> CARTERA_TIPOS_DOC { get; set; }
        public virtual DbSet<CONDICIONES_COMERCIALES> CONDICIONES_COMERCIALES { get; set; }
        public virtual DbSet<INVENTARIO> INVENTARIO { get; set; }
        public virtual DbSet<LISTAS_PRECIOS> LISTAS_PRECIOS { get; set; }
        public virtual DbSet<PRODUCTOS> PRODUCTOS { get; set; }
        public virtual DbSet<PRODUCTOS_LINEAS> PRODUCTOS_LINEAS { get; set; }
        public virtual DbSet<PRODUCTOS_PRESENTACION> PRODUCTOS_PRESENTACION { get; set; }
        public virtual DbSet<TIPOS_CLIENTE> TIPOS_CLIENTE { get; set; }
        public virtual DbSet<TIPOS_IDENTIFICACION> TIPOS_IDENTIFICACION { get; set; }
        public virtual DbSet<BODEGA> BODEGA { get; set; }
        public virtual DbSet<TOKEN> TOKEN { get; set; }
        public virtual DbSet<CARGUE_DEVOLUCIONES> CARGUE_DEVOLUCIONES { get; set; }
        public virtual DbSet<CARGUE_PEDIDOS> CARGUE_PEDIDOS { get; set; }
        public virtual DbSet<DETALLE_DEVOLUCIONES> DETALLE_DEVOLUCIONES { get; set; }
        public virtual DbSet<DETALLE_PEDIDOS> DETALLE_PEDIDOS { get; set; }
        public virtual DbSet<ENCABEZADO_DEVOLUCIONES> ENCABEZADO_DEVOLUCIONES { get; set; }
        public virtual DbSet<ENCABEZADO_PEDIDOS> ENCABEZADO_PEDIDOS { get; set; }
        public virtual DbSet<ENCABEZADO_RECAUDOS> ENCABEZADO_RECAUDOS { get; set; }
        public virtual DbSet<LISTA_DIF_RECAUDO> LISTA_DIF_RECAUDO { get; set; }
        public virtual DbSet<LISTA_FACT_RECAUDO> LISTA_FACT_RECAUDO { get; set; }
        public virtual DbSet<LISTA_PAG_RECAUDO> LISTA_PAG_RECAUDO { get; set; }
        public virtual DbSet<CLIENTES_CONTACTOS> CLIENTES_CONTACTOS { get; set; }
        public virtual DbSet<CLIENTES_UBICACIONES> CLIENTES_UBICACIONES { get; set; }
        public virtual DbSet<MAESTROS_LISTAS_PRECIOS> MAESTROS_LISTAS_PRECIOS { get; set; }
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<CONDICION_PAGO> CONDICION_PAGO { get; set; }
        public virtual DbSet<ARTICULO_PRECIO> ARTICULO_PRECIO { get; set; }
        public virtual DbSet<CLASIFICACION> CLASIFICACION { get; set; }
        public virtual DbSet<ViewAsignacion_Clientes> ViewAsignacion_Clientes { get; set; }
        public virtual DbSet<ViewCARTERA_DOCUMENTOS> ViewCARTERA_DOCUMENTOS { get; set; }
        public virtual DbSet<ViewCLIENTES_CONTACTOS> ViewCLIENTES_CONTACTOS { get; set; }
        public virtual DbSet<ViewCLIENTES_UBICACIONES> ViewCLIENTES_UBICACIONES { get; set; }
        public virtual DbSet<ViewPRODUCTOS_PRESENTACION> ViewPRODUCTOS_PRESENTACION { get; set; }
        public virtual DbSet<ViewFACTURA_RECAUDO> ViewFACTURA_RECAUDO { get; set; }
        public virtual DbSet<ViewPAGO_RECAUDO> ViewPAGO_RECAUDO { get; set; }
        public virtual DbSet<ViewPRODUCTO_DEVUELTOS> ViewPRODUCTO_DEVUELTOS { get; set; }
        public virtual DbSet<TIPO_NIT> TIPO_NIT { get; set; }
        public virtual DbSet<IMPUESTO> IMPUESTO { get; set; }
    }
}
