//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Insupan
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        public string PRODUCTO_ID { get; set; }
        public string LINEA_ID { get; set; }
        public string PRESENTACION_ID { get; set; }
        public string NOMBRE_PRODUCTO { get; set; }
        public Nullable<decimal> VALOR_PORCENTAJE_IVA { get; set; }
        public Nullable<decimal> ORDEN { get; set; }
        public Nullable<decimal> UNIDADES_BASE { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public Nullable<decimal> PRECIO_MINIMO { get; set; }
        public string CAMPO1 { get; set; }
        public string CAMPO2 { get; set; }
        public string CAMPO3 { get; set; }
        public string CAMPO4 { get; set; }
        public string CAMPO5 { get; set; }
        public string CAMPO6 { get; set; }
        public string CAMPO7 { get; set; }
        public string CAMPO8 { get; set; }
        public string CAMPO9 { get; set; }
        public string CAMPO10 { get; set; }
    }
}
