//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Insupan
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOS_CLIENTE
    {
        public string TIPO_CLIENTE_ID { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> DESCUENTO_COMERCIAL { get; set; }
        public Nullable<decimal> DESCUENTO_FINANCIERO1 { get; set; }
        public Nullable<decimal> DESCUENTO_FINANCIERO2 { get; set; }
        public Nullable<decimal> DESCUENTO_FINANCIERO3 { get; set; }
    }
}
