//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Insupan
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPRODUCTO_DEVUELTOS
    {
        public string DEVOLUCION_ID { get; set; }
        public string ASESOR_ID { get; set; }
        public string PRODUCTO_ID { get; set; }
        public string PRESENTACION_ID { get; set; }
        public decimal CANTIDAD { get; set; }
    }
}
