//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Insupan
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFACTURA_RECAUDO
    {
        public string RECAUDO_ID { get; set; }
        public string FACTURA_ID { get; set; }
        public decimal SALDO_ANTERIOR { get; set; }
        public decimal VALOR_PAGO { get; set; }
        public decimal VALOR_DESCUENTO_FINANCIERO { get; set; }
    }
}
