//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Insupan
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPRODUCTOS_PRESENTACION
    {
        public string PRODUCTO_ID { get; set; }
        public string PRESENTACION_ID { get; set; }
        public string NOMBRE_PRESENTACION { get; set; }
        public string CONTENIDO_UNIDADES_BASE { get; set; }
        public string CAMPO1 { get; set; }
        public string CAMPO2 { get; set; }
        public string CAMPO3 { get; set; }
        public string CAMPO4 { get; set; }
    }
}
