//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio.Insupan
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCARTERA_DOCUMENTOS
    {
        public string DOCUMENTO { get; set; }
        public string CLIENTE_ID { get; set; }
        public string TIPO { get; set; }
        public string NUMERO_REFERENCIA { get; set; }
        public string DOCUMENTO_GLOBAL { get; set; }
        public System.DateTime FECHA_DOCUMENTO { get; set; }
        public System.DateTime FECHA_BASE { get; set; }
        public System.DateTime FECHA_VENCIMIENTO { get; set; }
        public decimal VALOR_BASE { get; set; }
        public decimal VALOR_TOTAL { get; set; }
        public decimal SALDO_PENDIENTE { get; set; }
        public string CONDICIONES_COMERCIALES { get; set; }
        public decimal PORCENTAJE_DESCUENTO1 { get; set; }
        public decimal VALOR_IVA { get; set; }
        public string OBSERVACIONES { get; set; }
    }
}
